version: 2

sources:
  - name: tpch
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: orders
        columns:
          - name: o_orderkey
            tests:
              - unique
              - not_null
          - name: o_orderstatus
            tests:
              - accepted_values:
                  values: ['P', 'F', 'O']
          - name: o_custkey
            tests:
              - relationships:
                  to: source('tpch', 'customer')
                  field: c_custkey
      - name: lineitem
        columns:
          - name: l_orderkey
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'orders')
                  field: o_orderkey
      - name: nation
        columns:
          - name: n_nationkey
            tests:
              - unique
              - not_null
      - name: customer
        columns:
          - name: c_nationkey
            tags: [test_tag]
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'nation')
                  field: n_nationkey
          